export const inputEmail = ({
  sender,
  setSender,
  required,
  subject,
  setSubject,
  message,
  setMessage,
  multiline,
}) => [
  {
    id: "input-sender",
    type: "text",
    placeholder: "Sender",
    value: sender,
    onChange: (e) => setSender(e.target.value),
    color: "bg-gray-100",
    required: required,
  },
  {
    id: "input-subject",
    type: "text",
    placeholder: "Subject",
    value: subject,
    onChange: (e) => setSubject(e.target.value),
    color: "bg-gray-100",
    required: required,
  },
  {
    id: "input-content",
    type: multiline ? "textarea" : "text",
    placeholder: "Content",
    value: message,
    onChange: (e) => setMessage(e.target.value),
    color: "bg-gray-100",
    required: required,
    multiline: multiline,
  },
];
